# Generated by Django 3.0.4 on 2020-03-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0006_auto_20200306_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizacja', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.RemoveField(
            model_name='zleceniabadan',
            name='kategoria',
        ),
        migrations.AlterField(
            model_name='dodatkowebadania',
            name='edycja',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='imię',
            name='imię',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='nazwisko',
            name='nazwisko',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='placowka',
            name='nazwa',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Kategoria',
        ),
        migrations.AddField(
            model_name='zleceniabadan',
            name='termin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ZleceniaBadan.Termin'),
        ),
    ]
