# Generated by Django 3.0.4 on 2020-03-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0007_auto_20200313_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termin',
            options={'verbose_name': 'Termin', 'verbose_name_plural': 'Terminy'},
        ),
    ]
