# Generated by Django 3.0.4 on 2020-03-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0010_auto_20200313_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zleceniabadan',
            old_name='DataWystawiona',
            new_name='Data_Wystawionia',
        ),
    ]
