# Generated by Django 3.0.4 on 2020-03-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0013_auto_20200313_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZleceniaBadań',
            new_name='Zlecenia_Badań',
        ),
    ]
