# Generated by Django 3.0.4 on 2020-03-13 20:21

import ZleceniaBadan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0020_auto_20200313_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zleceniabadan',
            name='imię',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=ZleceniaBadan.models.Imię),
        ),
        migrations.AlterField(
            model_name='zleceniabadan',
            name='nazwisko',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=ZleceniaBadan.models.Nazwisko),
        ),
    ]
