# Generated by Django 3.0.4 on 2020-03-14 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0024_auto_20200313_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zleceniabadan',
            old_name='Data_wystawienia',
            new_name='data_wystawienia',
        ),
        migrations.RemoveField(
            model_name='zleceniabadan',
            name='nrZlecenia',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=120)),
                ('stars', models.IntegerField(default=5)),
                ('zlecenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZleceniaBadan.ZleceniaBadan')),
            ],
        ),
    ]
