# Generated by Django 3.0.4 on 2020-03-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0026_auto_20200315_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(blank=True, default='0', max_length=120),
        ),
    ]
