# Generated by Django 3.0.4 on 2020-03-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0029_auto_20200315_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(blank=True, default=1, max_length=120),
        ),
    ]
