# Generated by Django 2.0.6 on 2020-03-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0030_auto_20200315_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='zlecenie',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
