# Generated by Django 3.0.4 on 2020-03-15 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0003_auto_20200315_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='zleceniabadan',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(3, 'BARDZO_ZLY'), (1, 'DOBRY'), (3, 'NIE_WYLECZALNY'), (2, 'SLABY'), (0, 'Nieznany')], default=0),
        ),
        migrations.AlterField(
            model_name='zleceniabadan',
            name='badanie',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='zleceniabadan',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ZleceniaBadan.ExtraInfo'),
        ),
    ]
