# Generated by Django 2.0.6 on 2020-03-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0004_auto_20200315_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zleceniabadan',
            name='info',
        ),
        migrations.AlterField(
            model_name='zleceniabadan',
            name='badanie',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='ExtraInfo',
        ),
    ]
