# Generated by Django 2.0.6 on 2020-03-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0005_auto_20200315_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zleceniabadan',
            name='placówka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ZleceniaBadan.Placowka'),
        ),
    ]
