# Generated by Django 3.0.4 on 2020-03-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0014_auto_20200313_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zlecenia_Badań',
            new_name='ZleceniaBadan',
        ),
    ]
