# Generated by Django 3.0.4 on 2020-03-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0018_auto_20200313_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WynikiBadań',
        ),
        migrations.AlterModelOptions(
            name='wynikpn',
            options={'verbose_name': 'WynikPN', 'verbose_name_plural': 'WynikiPN'},
        ),
    ]
