# Generated by Django 3.0.4 on 2020-03-13 20:32

import ZleceniaBadan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0021_auto_20200313_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zleceniabadan',
            name='badanie',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='zleceniabadan',
            name='imię',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name=ZleceniaBadan.models.Imię),
        ),
        migrations.AlterField(
            model_name='zleceniabadan',
            name='nazwisko',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name=ZleceniaBadan.models.Nazwisko),
        ),
    ]
