# Generated by Django 3.0.4 on 2020-03-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0025_auto_20200315_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(default='', max_length=120),
        ),
    ]
