# Generated by Django 3.0.4 on 2020-03-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0009_zleceniabadan_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zleceniabadan',
            name='data',
        ),
        migrations.AddField(
            model_name='zleceniabadan',
            name='DataWystawiona',
            field=models.DateField(blank=True, null=True),
        ),
    ]
