# Generated by Django 3.0.4 on 2020-03-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0011_auto_20200313_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zleceniabadan',
            old_name='Data_Wystawionia',
            new_name='Data_wystawienia',
        ),
        migrations.RenameField(
            model_name='zleceniabadan',
            old_name='dodatkoweBadania',
            new_name='dodatkowe_badania',
        ),
        migrations.RenameField(
            model_name='zleceniabadan',
            old_name='placowka',
            new_name='placówka',
        ),
    ]
