# Generated by Django 3.0.4 on 2020-03-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0012_auto_20200313_1414'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZleceniaBadan',
            new_name='ZleceniaBadań',
        ),
        migrations.AlterModelOptions(
            name='dodatkowebadania',
            options={'verbose_name': 'Dodatkowe Badanie', 'verbose_name_plural': 'Dodatkowe Badania'},
        ),
    ]
