# Generated by Django 3.0.4 on 2020-03-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0017_auto_20200313_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zleceniabadan',
            old_name='wynik',
            new_name='wynikPN',
        ),
    ]
