# Generated by Django 3.0.4 on 2020-03-13 20:41

import ZleceniaBadan.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0022_auto_20200313_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nazwisko',
            name='nazwisko',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='zleceniabadan',
            name='badanie',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='zleceniabadan',
            name='imię',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ZleceniaBadan.Imię'),
        ),
        migrations.AlterField(
            model_name='zleceniabadan',
            name='nazwisko',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=ZleceniaBadan.models.Nazwisko),
        ),
    ]
