# Generated by Django 3.0.4 on 2020-03-13 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZleceniaBadan', '0023_auto_20200313_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='zleceniabadan',
            name='nrZlecenia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nazwisko',
            name='nazwisko',
            field=models.CharField(default=2, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wynikibadań',
            name='wynik',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='zleceniabadan',
            name='nazwisko',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ZleceniaBadan.Nazwisko'),
        ),
    ]
